- "::" instead of "REM" inside a if () in batch is evil and can cause a really nice mess from time to time. - Changing one "exit" to "exit /b" was not nice from me in the past. ARM build now prepares host tools nicely again and you can build em. ARM build itself dies very early due to ..\..\boot\freeldr\freeldr\arch\arm\boot.S(9) : fatal error C1083: Cannot open include file: 'ksarm.h': No such file or directory
svn path=/trunk/; revision=69191