[SYSSETUP] Fix broken build on RosBE2.1.6 CORE-17028
The build broke due to a typo introduced by
0.4.15-dev-275-g
612729b09272aeb693e156de6b5991891951dbf2

../dll/win32/syssetup/wizard.c: In function 'ProductPageDlgProc':
../dll/win32/syssetup/wizard.c:527:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-
after-statement]
cc1.exe: all warnings being treated as errors